lib/cgraph: include empty malloc.h from subdir include
Having it directly in cgraph/ means that this file is found by all
other libs with `-Ilib/cgraph/`. Since it is only needed by cgraph we
can move it to a subdirectory and add `-Iinclude/` to the cgraph
Makefile. If the other libraries and plugins picks up the empty
malloc.h it causes problems on some systems when compiling for example
lib/sfdpgen/PriorityQueue.c and plugin/visio/VisioGraphic.cpp where it
gives errors like:

```
/storage/termux-build/graphviz/src/lib/sfdpgen/PriorityQueue.c:96:40: error: use of undeclared identifier 'free'; did you mean 'frexp'?
    DoubleLinkedList_delete_element(l, free, &((q->buckets)[gainold]));
                                       ^~~~
                                       frexp
```
and
```
[...]
In file included from /storage/termux-build/graphviz/src/plugin/visio/VisioGraphic.cpp:16:
In file included from /storage/termux-build/_cache/android-r20-api-24-v3/bin/../sysroot/usr/include/c++/v1/algorithm:644:
In file included from /storage/termux-build/_cache/android-r20-api-24-v3/bin/../sysroot/usr/include/c++/v1/memory:654:
In file included from /storage/termux-build/_cache/android-r20-api-24-v3/bin/../sysroot/usr/include/c++/v1/typeinfo:61:
In file included from /storage/termux-build/_cache/android-r20-api-24-v3/bin/../sysroot/usr/include/c++/v1/exception:82:
/storage/termux-build/_cache/android-r20-api-24-v3/bin/../sysroot/usr/include/c++/v1/cstdlib:125:9: error: no member named 'calloc' in the global namespace
using ::calloc;
      ~~^
[...]
```

On other systems the compilation succeeds but with warnings like

```
../../../lib/common/memory.c:47:10: warning: implicitly declaring library function 'malloc' with type 'void *(unsigned long)' [-Wimplicit-function-declaration]
```